arch_demo
jarviscanada/jarvis_data_eng_aayushi pull request #1
Opened 2019-11-27 01:30 UTC by aayushi93

Ticket URL - https://www.notion.so/Architecture-Demo-9ff91b0b97bc46709006d4f33e35b080

2019-11-30 20:14 UTC, jaypatel-jrvs requested changes

2019-11-30 20:14 UTC, jaypatel-jrvs commented on linux_sql/README.md
> +![LCA Architecture](./assets/Monitor_Agent_Architecture.png.png)
Image does not load.

2019-12-01 00:13 UTC, aayushi93 commented on linux_sql/README.md
> +![LCA Architecture](./assets/Monitor_Agent_Architecture.png.png)
Issue fixed. The image is now loading.

2019-12-01 00:41 UTC, jaypatel-jrvs approved these changes

2019-12-01 05:02 UTC, merged